-- Add unified extraction artifact kinds to PdfModelArtifactKind enum
ALTER TYPE "PdfModelArtifactKind" ADD VALUE 'UNIFIED_PARSER_DOCUMENT';
ALTER TYPE "PdfModelArtifactKind" ADD VALUE 'UNIFIED_FINANCIAL_EXTRACTION';
ALTER TYPE "PdfModelArtifactKind" ADD VALUE 'UNIFIED_NARRATIVE_EXTRACTION';
ALTER TYPE "PdfModelArtifactKind" ADD VALUE 'LEGACY_VS_UNIFIED_EXTRACTION_COMPARISON';
