import { prisma } from "@/lib/prisma";
import { NormalizedCompany } from "@/lib/types";
import { AddressType, CompanyStatus } from "@prisma/client";

export async function upsertCompanySnapshot(company: NormalizedCompany) {
  const industryCode = company.industryCode && await prisma.industryCode.upsert({
    where: { code: company.industryCode.code },
    update: {
      title: company.industryCode.title,
      description: company.industryCode.description,
      level: company.industryCode.level,
      sourceSystem: company.industryCode.sourceSystem,
      sourceEntityType: company.industryCode.sourceEntityType,
      sourceId: company.industryCode.sourceId,
      fetchedAt: company.industryCode.fetchedAt,
      normalizedAt: company.industryCode.normalizedAt,
      rawPayload: company.industryCode.rawPayload as never,
    },
    create: {
      code: company.industryCode.code,
      title: company.industryCode.title,
      description: company.industryCode.description,
      level: company.industryCode.level,
      sourceSystem: company.industryCode.sourceSystem,
      sourceEntityType: company.industryCode.sourceEntityType,
      sourceId: company.industryCode.sourceId,
      fetchedAt: company.industryCode.fetchedAt,
      normalizedAt: company.industryCode.normalizedAt,
      rawPayload: company.industryCode.rawPayload as never,
    },
  });

  await prisma.company.upsert({
    where: { orgNumber: company.orgNumber },
    update: {
      slug: company.slug,
      name: company.name,
      legalForm: company.legalForm,
      status: company.status as CompanyStatus,
      registeredAt: company.registeredAt,
      foundedAt: company.foundedAt,
      website: company.website,
      employeeCount: company.employeeCount,
      revenue: company.revenue,
      operatingProfit: company.operatingProfit,
      netIncome: company.netIncome,
      equity: company.equity,
      description: company.description,
      sourceSystem: company.sourceSystem,
      sourceEntityType: company.sourceEntityType,
      sourceId: company.sourceId,
      fetchedAt: company.fetchedAt,
      normalizedAt: company.normalizedAt,
      rawPayload: company.rawPayload as never,
      industryCodeId: industryCode?.id,
      addresses: {
        deleteMany: {},
        create: company.addresses.map((address) => ({
          type: AddressType.BUSINESS,
          line1: address.line1,
          line2: address.line2,
          postalCode: address.postalCode,
          city: address.city,
          region: address.region,
          country: address.country,
          sourceSystem: address.sourceSystem,
          sourceEntityType: address.sourceEntityType,
          sourceId: address.sourceId,
          fetchedAt: address.fetchedAt,
          normalizedAt: address.normalizedAt,
          rawPayload: address.rawPayload as never,
        })),
      },
    },
    create: {
      slug: company.slug,
      orgNumber: company.orgNumber,
      name: company.name,
      legalForm: company.legalForm,
      status: company.status as CompanyStatus,
      registeredAt: company.registeredAt,
      foundedAt: company.foundedAt,
      website: company.website,
      employeeCount: company.employeeCount,
      revenue: company.revenue,
      operatingProfit: company.operatingProfit,
      netIncome: company.netIncome,
      equity: company.equity,
      description: company.description,
      sourceSystem: company.sourceSystem,
      sourceEntityType: company.sourceEntityType,
      sourceId: company.sourceId,
      fetchedAt: company.fetchedAt,
      normalizedAt: company.normalizedAt,
      rawPayload: company.rawPayload as never,
      industryCodeId: industryCode?.id,
      addresses: {
        create: company.addresses.map((address) => ({
          type: AddressType.BUSINESS,
          line1: address.line1,
          line2: address.line2,
          postalCode: address.postalCode,
          city: address.city,
          region: address.region,
          country: address.country,
          sourceSystem: address.sourceSystem,
          sourceEntityType: address.sourceEntityType,
          sourceId: address.sourceId,
          fetchedAt: address.fetchedAt,
          normalizedAt: address.normalizedAt,
          rawPayload: address.rawPayload as never,
        })),
      },
    },
  });
}