export const COMPANY_EVENT_TYPES = [
  "capital_raise",
  "share_issue",
  "debt_refinancing",
  "bond_issue",
  "dividend",
  "buyback",
  "listing",
  "delisting",
  "earnings",
  "annual_report",
  "financial_statement",
  "reporting_calendar",
  "profit_warning",
  "guidance_upgrade",
  "guidance_downgrade",
  "margin_pressure",
  "cash_flow_issue",
  "mna",
  "asset_sale",
  "spin_off",
  "restructuring",
  "strategic_review",
  "contract_award",
  "procurement_tender",
  "contract_loss",
  "production_update",
  "capacity_expansion",
  "project_delay",
  "cost_overrun",
  "investigation",
  "fine",
  "license_award",
  "license_loss",
  "legal_settlement",
  "lawsuit",
  "tax_dispute",
  "regulatory_approval",
  "regulatory_change",
  "bankruptcy",
  "reconstruction",
  "liquidation",
  "forced_dissolution",
  "auditor_warning",
  "going_concern_risk",
  "ceo_change",
  "cfo_change",
  "board_change",
  "auditor_change",
  "insider_transaction",
  "ownership_change",
  "commodity_price_exposure",
  "interest_rate_exposure",
  "peer_read_across",
  "sector_news",
  "macro_news",
  "product_launch",
  "analyst_comment",
  "low_signal_mention",
  "other",
] as const;

export type CompanyEventType = (typeof COMPANY_EVENT_TYPES)[number];

export type EventDirection = "positive" | "negative" | "mixed" | "neutral" | "unknown";
export type EventImpactHorizon = "immediate" | "short_term" | "medium_term" | "long_term";
export type EventConfidenceLevel = "high" | "medium" | "low";

export type EventClassification = {
  eventType: CompanyEventType;
  eventTypeScore: number;
  materialityScore: number;
  financialImpactScore: number;
  strategicImpactScore: number;
  riskImpactScore: number;
  direction: EventDirection;
  impactHorizon: EventImpactHorizon | null;
  confidenceLevel: EventConfidenceLevel;
  explanation: Record<string, unknown>;
};

export type EventRule = {
  eventType: CompanyEventType;
  keywords: string[];
  materialityScore: number;
  financialImpactScore: number;
  strategicImpactScore: number;
  riskImpactScore: number;
  direction: EventDirection;
  impactHorizon: EventImpactHorizon | null;
};

export const EVENT_CLASSIFICATION_RULES: EventRule[] = [
  {
    eventType: "annual_report",
    keywords: [
      "annual report",
      "annual and sustainability reports",
      "arsrapport",
      "arsregnskap",
    ],
    materialityScore: 0.78,
    financialImpactScore: 0.82,
    strategicImpactScore: 0.42,
    riskImpactScore: 0.35,
    direction: "neutral",
    impactHorizon: "immediate",
  },
  {
    eventType: "financial_statement",
    keywords: ["financial statement", "financial statements", "regnskap", "halvarsrapport", "half-year report", "interim report", "delarsrapport"],
    materialityScore: 0.74,
    financialImpactScore: 0.8,
    strategicImpactScore: 0.34,
    riskImpactScore: 0.34,
    direction: "neutral",
    impactHorizon: "immediate",
  },
  {
    eventType: "earnings",
    keywords: ["quarterly report", "q1", "q2", "q3", "q4", "resultat", "earnings", "financial results"],
    materialityScore: 0.78,
    financialImpactScore: 0.84,
    strategicImpactScore: 0.38,
    riskImpactScore: 0.36,
    direction: "neutral",
    impactHorizon: "immediate",
  },
  {
    eventType: "reporting_calendar",
    keywords: [
      "invitation to results presentation",
      "invitation to presentation of",
      "invitation to q1",
      "invitation to q2",
      "invitation to q3",
      "invitation to q4",
      "financial calendar",
      "to publish q1",
      "to publish q2",
      "to publish q3",
      "to publish q4",
      "invitasjon til resultatpresentasjon",
      "finansiell kalender",
    ],
    materialityScore: 0.38,
    financialImpactScore: 0.24,
    strategicImpactScore: 0.16,
    riskImpactScore: 0.1,
    direction: "neutral",
    impactHorizon: "immediate",
  },
  {
    eventType: "profit_warning",
    keywords: ["profit warning", "resultatvarsel", "varsler resultatfall", "svakere resultat", "lower profit", "earnings warning"],
    materialityScore: 0.9,
    financialImpactScore: 0.9,
    strategicImpactScore: 0.46,
    riskImpactScore: 0.76,
    direction: "negative",
    impactHorizon: "immediate",
  },
  {
    eventType: "guidance_upgrade",
    keywords: ["raises guidance", "guidance upgrade", "oppjusterer guiding", "hever guiding", "hever utsiktene"],
    materialityScore: 0.8,
    financialImpactScore: 0.82,
    strategicImpactScore: 0.5,
    riskImpactScore: 0.22,
    direction: "positive",
    impactHorizon: "short_term",
  },
  {
    eventType: "guidance_downgrade",
    keywords: ["cuts guidance", "guidance downgrade", "nedjusterer guiding", "senker guiding", "senker utsiktene"],
    materialityScore: 0.84,
    financialImpactScore: 0.84,
    strategicImpactScore: 0.5,
    riskImpactScore: 0.68,
    direction: "negative",
    impactHorizon: "short_term",
  },
  {
    eventType: "margin_pressure",
    keywords: ["margin pressure", "marginfall", "lavere marginer", "svakere marginer", "cost inflation", "kostnadspress"],
    materialityScore: 0.74,
    financialImpactScore: 0.78,
    strategicImpactScore: 0.38,
    riskImpactScore: 0.58,
    direction: "negative",
    impactHorizon: "short_term",
  },
  {
    eventType: "cash_flow_issue",
    keywords: ["cash flow issue", "negative cash flow", "likviditetsproblem", "likviditetsutfordring", "working capital pressure"],
    materialityScore: 0.84,
    financialImpactScore: 0.86,
    strategicImpactScore: 0.46,
    riskImpactScore: 0.82,
    direction: "negative",
    impactHorizon: "immediate",
  },
  {
    eventType: "sector_news",
    keywords: [
      "semiconductor stocks",
      "chip stocks",
      "ai stocks",
      "semiconductor",
      "semiconductors",
      "memory chips",
      "foundry",
      "nvidia",
      "asml",
      "tsmc",
      "amd",
      "broadcom",
      "datacenter",
      "data center",
      "ai demand",
      "ai growth",
      "growth forecasts",
      "supply-demand",
      "sell-off",
      "selloff",
      "stocks fall",
      "shares fall",
    ],
    materialityScore: 0.74,
    financialImpactScore: 0.58,
    strategicImpactScore: 0.62,
    riskImpactScore: 0.52,
    direction: "mixed",
    impactHorizon: "medium_term",
  },
  {
    eventType: "macro_news",
    keywords: [
      "global markets",
      "equity markets",
      "risk appetite",
      "gdp",
      "economic growth",
      "growth expectations",
      "productivity growth",
      "investment cycle",
      "capital expenditure",
      "capex",
      "consumer demand",
      "business investment",
      "ai growth",
      "artificial intelligence boom",
    ],
    materialityScore: 0.72,
    financialImpactScore: 0.56,
    strategicImpactScore: 0.58,
    riskImpactScore: 0.5,
    direction: "mixed",
    impactHorizon: "medium_term",
  },
  {
    eventType: "contract_loss",
    keywords: [
      "contract loss",
      "lost contract",
      "loses contract",
      "terminates contract",
      "terminated agreement",
      "mister kontrakt",
      "taper kontrakt",
      "kontrakt terminert",
    ],
    materialityScore: 0.78,
    financialImpactScore: 0.74,
    strategicImpactScore: 0.58,
    riskImpactScore: 0.62,
    direction: "negative",
    impactHorizon: "short_term",
  },
  {
    eventType: "contract_award",
    keywords: [
      "contract award",
      "wins contract",
      "new contract",
      "contract extension",
      "customer contract",
      "lease contract",
      "commercial agreement",
      "strategic partnership",
      "purchase order",
      "order intake",
      "letter of intent",
      "tildelt kontrakt",
      "vinner kontrakt",
      "ny kontrakt",
      "rammeavtale",
      "kundeavtale",
      "leieavtale",
      "samarbeidsavtale",
      "partneravtale",
      "intensjonsavtale",
    ],
    materialityScore: 0.72,
    financialImpactScore: 0.68,
    strategicImpactScore: 0.62,
    riskImpactScore: 0.22,
    direction: "positive",
    impactHorizon: "short_term",
  },
  {
    eventType: "procurement_tender",
    keywords: [
      "invites tender",
      "launches tender",
      "tender process",
      "tender for",
      "seeks bids",
      "seeking bids",
      "seeks suppliers",
      "seeking suppliers",
      "procurement process",
      "installation vessel",
      "installation vessels",
      "utlyser anbud",
      "anbudsprosess",
      "soker leverandorer",
    ],
    materialityScore: 0.68,
    financialImpactScore: 0.56,
    strategicImpactScore: 0.66,
    riskImpactScore: 0.24,
    direction: "neutral",
    impactHorizon: "medium_term",
  },
  {
    eventType: "capital_raise",
    keywords: ["capital raise", "kapitalinnhenting", "private placement", "rettet emisjon", "emisjon"],
    materialityScore: 0.86,
    financialImpactScore: 0.86,
    strategicImpactScore: 0.58,
    riskImpactScore: 0.54,
    direction: "mixed",
    impactHorizon: "immediate",
  },
  {
    eventType: "share_issue",
    keywords: ["share issue", "new shares", "rights issue", "repair issue", "aksjeemisjon", "fortrinnsrettsemisjon", "reparasjonsemisjon"],
    materialityScore: 0.82,
    financialImpactScore: 0.78,
    strategicImpactScore: 0.54,
    riskImpactScore: 0.5,
    direction: "mixed",
    impactHorizon: "immediate",
  },
  {
    eventType: "debt_refinancing",
    keywords: ["debt refinancing", "refinancing", "refinances debt", "refinansierer gjeld", "refinansiering", "ny laneavtale", "ny lanefasilitet"],
    materialityScore: 0.78,
    financialImpactScore: 0.82,
    strategicImpactScore: 0.46,
    riskImpactScore: 0.58,
    direction: "mixed",
    impactHorizon: "short_term",
  },
  {
    eventType: "bond_issue",
    keywords: ["bond issue", "bond loan", "senior secured bond", "issues bonds", "obligasjonslan", "utsteder obligasjonslan", "gront obligasjonslan"],
    materialityScore: 0.76,
    financialImpactScore: 0.78,
    strategicImpactScore: 0.44,
    riskImpactScore: 0.48,
    direction: "mixed",
    impactHorizon: "short_term",
  },
  {
    eventType: "buyback",
    keywords: [
      "buy-back",
      "buyback",
      "tilbakekjop",
      "egne aksjer",
      "own shares",
      "issuer s own shares",
      "issuer's own shares",
      "acquisition or disposal of an issuer s own shares",
      "acquisition or disposal of an issuer's own shares",
    ],
    materialityScore: 0.58,
    financialImpactScore: 0.52,
    strategicImpactScore: 0.34,
    riskImpactScore: 0.12,
    direction: "positive",
    impactHorizon: "short_term",
  },
  {
    eventType: "dividend",
    keywords: ["dividend", "utbytte", "cash dividend"],
    materialityScore: 0.66,
    financialImpactScore: 0.72,
    strategicImpactScore: 0.28,
    riskImpactScore: 0.16,
    direction: "positive",
    impactHorizon: "immediate",
  },
  {
    eventType: "listing",
    keywords: [
      "stock exchange listing",
      "share listed in europe",
      "ipo",
      "initial public offering",
      "lists shares",
      "first day of trading",
      "notering",
      "borsnotering",
      "opptak til handel",
    ],
    materialityScore: 0.82,
    financialImpactScore: 0.62,
    strategicImpactScore: 0.78,
    riskImpactScore: 0.38,
    direction: "positive",
    impactHorizon: "immediate",
  },
  {
    eventType: "delisting",
    keywords: ["delisting", "delists shares", "taken private", "stryking fra bors", "strykes fra bors", "avnotering", "siste handelsdag"],
    materialityScore: 0.84,
    financialImpactScore: 0.62,
    strategicImpactScore: 0.72,
    riskImpactScore: 0.58,
    direction: "mixed",
    impactHorizon: "immediate",
  },
  {
    eventType: "mna",
    keywords: [
      "acquisition",
      "acquires",
      "merger",
      "takeover",
      "buys company",
      "selger selskap",
      "kjoper selskap",
      "fusjon",
      "oppkjop",
      "budplikt",
      "mandatory offer",
    ],
    materialityScore: 0.84,
    financialImpactScore: 0.68,
    strategicImpactScore: 0.84,
    riskImpactScore: 0.48,
    direction: "mixed",
    impactHorizon: "medium_term",
  },
  {
    eventType: "asset_sale",
    keywords: ["asset sale", "divestment", "sells assets", "selger eiendel", "selger portefolje", "salg av virksomhet"],
    materialityScore: 0.74,
    financialImpactScore: 0.66,
    strategicImpactScore: 0.68,
    riskImpactScore: 0.36,
    direction: "mixed",
    impactHorizon: "short_term",
  },
  {
    eventType: "spin_off",
    keywords: ["spin-off", "spinoff", "demerger", "fisjon", "skiller ut virksomhet"],
    materialityScore: 0.74,
    financialImpactScore: 0.52,
    strategicImpactScore: 0.78,
    riskImpactScore: 0.36,
    direction: "mixed",
    impactHorizon: "medium_term",
  },
  {
    eventType: "restructuring",
    keywords: ["restructuring", "cost reduction", "downsizing", "nedbemanning", "restrukturering", "spareprogram", "kostnadskutt"],
    materialityScore: 0.74,
    financialImpactScore: 0.7,
    strategicImpactScore: 0.56,
    riskImpactScore: 0.56,
    direction: "mixed",
    impactHorizon: "medium_term",
  },
  {
    eventType: "strategic_review",
    keywords: ["strategic review", "strategisk gjennomgang", "vurderer strategiske alternativer", "review of strategic alternatives"],
    materialityScore: 0.68,
    financialImpactScore: 0.42,
    strategicImpactScore: 0.78,
    riskImpactScore: 0.38,
    direction: "mixed",
    impactHorizon: "medium_term",
  },
  {
    eventType: "production_update",
    keywords: [
      "production update",
      "operational update",
      "traffic figures",
      "monthly traffic update",
      "unit revenue growth and adjusted capacity",
      "passenger traffic update",
      "produksjonsoppdatering",
      "produksjonsrapport",
      "volumoppdatering",
      "trafikktall",
    ],
    materialityScore: 0.66,
    financialImpactScore: 0.64,
    strategicImpactScore: 0.42,
    riskImpactScore: 0.34,
    direction: "neutral",
    impactHorizon: "short_term",
  },
  {
    eventType: "capacity_expansion",
    keywords: ["capacity expansion", "expands capacity", "new factory", "new plant", "oker kapasitet", "ny fabrikk", "utvider produksjon"],
    materialityScore: 0.7,
    financialImpactScore: 0.58,
    strategicImpactScore: 0.76,
    riskImpactScore: 0.34,
    direction: "positive",
    impactHorizon: "long_term",
  },
  {
    eventType: "project_delay",
    keywords: ["project delay", "delayed project", "forsinket prosjekt", "utsetter prosjekt", "delay in construction", "forsinkelse"],
    materialityScore: 0.76,
    financialImpactScore: 0.68,
    strategicImpactScore: 0.54,
    riskImpactScore: 0.68,
    direction: "negative",
    impactHorizon: "short_term",
  },
  {
    eventType: "cost_overrun",
    keywords: ["cost overrun", "budget overrun", "higher capex", "kostnadssprekk", "budsjettsprekk", "hoyere investeringer"],
    materialityScore: 0.8,
    financialImpactScore: 0.78,
    strategicImpactScore: 0.42,
    riskImpactScore: 0.7,
    direction: "negative",
    impactHorizon: "short_term",
  },
  {
    eventType: "bankruptcy",
    keywords: ["bankruptcy", "konkurs", "bankrupt"],
    materialityScore: 0.98,
    financialImpactScore: 0.92,
    strategicImpactScore: 0.82,
    riskImpactScore: 0.98,
    direction: "negative",
    impactHorizon: "immediate",
  },
  {
    eventType: "reconstruction",
    keywords: ["reconstruction", "rekonstruksjon", "debt restructuring", "gjeldsforhandling"],
    materialityScore: 0.92,
    financialImpactScore: 0.86,
    strategicImpactScore: 0.72,
    riskImpactScore: 0.9,
    direction: "negative",
    impactHorizon: "immediate",
  },
  {
    eventType: "liquidation",
    keywords: ["liquidation", "avvikling", "opplosning"],
    materialityScore: 0.92,
    financialImpactScore: 0.82,
    strategicImpactScore: 0.74,
    riskImpactScore: 0.9,
    direction: "negative",
    impactHorizon: "immediate",
  },
  {
    eventType: "forced_dissolution",
    keywords: ["forced dissolution", "tvangsopplosning", "tvangsavvikling"],
    materialityScore: 0.88,
    financialImpactScore: 0.78,
    strategicImpactScore: 0.7,
    riskImpactScore: 0.88,
    direction: "negative",
    impactHorizon: "immediate",
  },
  {
    eventType: "investigation",
    keywords: ["investigation", "etterforskning", "tilsynssak", "gransking", "probe"],
    materialityScore: 0.82,
    financialImpactScore: 0.42,
    strategicImpactScore: 0.48,
    riskImpactScore: 0.86,
    direction: "negative",
    impactHorizon: "short_term",
  },
  {
    eventType: "fine",
    keywords: [
      "fined",
      "fine imposed",
      "regulatory fine",
      "administrative fine",
      "penalty imposed",
      "administrative penalty",
      "overtredelsesgebyr",
      "ilagt bot",
      "vedtatt bot",
      "fikk bot",
      "bot pa",
      "gebyr fra tilsyn",
    ],
    materialityScore: 0.72,
    financialImpactScore: 0.48,
    strategicImpactScore: 0.36,
    riskImpactScore: 0.76,
    direction: "negative",
    impactHorizon: "short_term",
  },
  {
    eventType: "license_award",
    keywords: ["license award", "awarded license", "tildelt lisens", "tildelt konsesjon", "production license"],
    materialityScore: 0.7,
    financialImpactScore: 0.48,
    strategicImpactScore: 0.72,
    riskImpactScore: 0.28,
    direction: "positive",
    impactHorizon: "medium_term",
  },
  {
    eventType: "license_loss",
    keywords: ["license revoked", "loses license", "mistet lisens", "mistet konsesjon", "tilbakekaller konsesjon"],
    materialityScore: 0.84,
    financialImpactScore: 0.68,
    strategicImpactScore: 0.74,
    riskImpactScore: 0.82,
    direction: "negative",
    impactHorizon: "short_term",
  },
  {
    eventType: "legal_settlement",
    keywords: ["settlement agreement with", "forliksavtale med"],
    materialityScore: 0.78,
    financialImpactScore: 0.62,
    strategicImpactScore: 0.44,
    riskImpactScore: 0.6,
    direction: "mixed",
    impactHorizon: "short_term",
  },
  {
    eventType: "lawsuit",
    keywords: ["lawsuit", "legal claim", "class action", "saksokt", "soksmal", "rettssak", "tvist"],
    materialityScore: 0.72,
    financialImpactScore: 0.44,
    strategicImpactScore: 0.36,
    riskImpactScore: 0.74,
    direction: "negative",
    impactHorizon: "medium_term",
  },
  {
    eventType: "tax_dispute",
    keywords: ["tax dispute", "tax claim", "skattekontroll", "skattekrav", "skattetvist", "bokettersyn"],
    materialityScore: 0.74,
    financialImpactScore: 0.56,
    strategicImpactScore: 0.3,
    riskImpactScore: 0.76,
    direction: "negative",
    impactHorizon: "medium_term",
  },
  {
    eventType: "regulatory_approval",
    keywords: [
      "regulatory approval",
      "approval of prospectus",
      "prospectus approved",
      "approved prospectus",
      "approved by the regulator",
      "approved by the authority",
      "marketing authorization",
      "godkjenning av prospekt",
      "prospekt godkjent",
      "myndighetsgodkjenning",
    ],
    materialityScore: 0.62,
    financialImpactScore: 0.38,
    strategicImpactScore: 0.52,
    riskImpactScore: 0.22,
    direction: "positive",
    impactHorizon: "short_term",
  },
  {
    eventType: "regulatory_change",
    keywords: ["regulation", "forskrift", "lovendring", "regulatory change", "sanksjonspakke", "sanctions package"],
    materialityScore: 0.7,
    financialImpactScore: 0.44,
    strategicImpactScore: 0.54,
    riskImpactScore: 0.62,
    direction: "mixed",
    impactHorizon: "medium_term",
  },
  {
    eventType: "auditor_warning",
    keywords: ["auditor warning", "qualified opinion", "presisering fra revisor", "forbehold i revisjonsberetning", "revisorforbehold"],
    materialityScore: 0.86,
    financialImpactScore: 0.72,
    strategicImpactScore: 0.42,
    riskImpactScore: 0.86,
    direction: "negative",
    impactHorizon: "immediate",
  },
  {
    eventType: "going_concern_risk",
    keywords: ["going concern", "continued operations risk", "fortsatt drift", "vesentlig usikkerhet", "driftsforutsetning"],
    materialityScore: 0.94,
    financialImpactScore: 0.88,
    strategicImpactScore: 0.58,
    riskImpactScore: 0.94,
    direction: "negative",
    impactHorizon: "immediate",
  },
  {
    eventType: "ceo_change",
    keywords: ["ceo", "chief executive", "konsernsjef", "administrerende direktor"],
    materialityScore: 0.66,
    financialImpactScore: 0.24,
    strategicImpactScore: 0.72,
    riskImpactScore: 0.42,
    direction: "mixed",
    impactHorizon: "short_term",
  },
  {
    eventType: "cfo_change",
    keywords: ["cfo", "chief financial officer", "finansdirektor", "ny finansdirektor", "okonomidirektor"],
    materialityScore: 0.58,
    financialImpactScore: 0.34,
    strategicImpactScore: 0.48,
    riskImpactScore: 0.38,
    direction: "mixed",
    impactHorizon: "short_term",
  },
  {
    eventType: "board_change",
    keywords: ["board", "styre", "chair", "chairman", "chairwoman", "chairperson", "styreleder"],
    materialityScore: 0.54,
    financialImpactScore: 0.18,
    strategicImpactScore: 0.54,
    riskImpactScore: 0.34,
    direction: "mixed",
    impactHorizon: "medium_term",
  },
  {
    eventType: "auditor_change",
    keywords: ["auditor change", "new auditor", "revisorbytte", "ny revisor", "fratrer som revisor"],
    materialityScore: 0.56,
    financialImpactScore: 0.24,
    strategicImpactScore: 0.28,
    riskImpactScore: 0.5,
    direction: "mixed",
    impactHorizon: "medium_term",
  },
  {
    eventType: "insider_transaction",
    keywords: [
      "insider transaction",
      "primary insider",
      "primary insiders",
      "mandatory notification of trade",
      "mandatory notification of trade primary insiders",
      "meldepliktig handel",
      "primarinnsider",
      "innsidehandel",
    ],
    materialityScore: 0.56,
    financialImpactScore: 0.34,
    strategicImpactScore: 0.34,
    riskImpactScore: 0.26,
    direction: "mixed",
    impactHorizon: "short_term",
  },
  {
    eventType: "ownership_change",
    keywords: ["ownership change", "major shareholder", "flagging", "flaggemelding", "storaksjonaer", "eierandel", "passes threshold"],
    materialityScore: 0.64,
    financialImpactScore: 0.38,
    strategicImpactScore: 0.6,
    riskImpactScore: 0.3,
    direction: "mixed",
    impactHorizon: "short_term",
  },
  {
    eventType: "interest_rate_exposure",
    keywords: ["policy rate", "styringsrente", "interest rate", "renteheving", "rentekutt"],
    materialityScore: 0.66,
    financialImpactScore: 0.62,
    strategicImpactScore: 0.32,
    riskImpactScore: 0.44,
    direction: "mixed",
    impactHorizon: "short_term",
  },
  {
    eventType: "commodity_price_exposure",
    keywords: [
      "oil price",
      "brent",
      "wti",
      "natural gas price",
      "natural gas market",
      "lng price",
      "lng prices",
      "lng market",
      "lng spot",
      "oljepris",
      "gasspris",
    ],
    materialityScore: 0.68,
    financialImpactScore: 0.66,
    strategicImpactScore: 0.38,
    riskImpactScore: 0.42,
    direction: "mixed",
    impactHorizon: "short_term",
  },
  {
    eventType: "product_launch",
    keywords: ["product launch", "launches product", "lanserer produkt", "produktlansering", "new platform"],
    materialityScore: 0.56,
    financialImpactScore: 0.38,
    strategicImpactScore: 0.58,
    riskImpactScore: 0.22,
    direction: "positive",
    impactHorizon: "medium_term",
  },
  {
    eventType: "analyst_comment",
    keywords: ["analyst upgrade", "analyst downgrade", "price target", "kursmal", "meglerhus", "analytiker"],
    materialityScore: 0.48,
    financialImpactScore: 0.32,
    strategicImpactScore: 0.26,
    riskImpactScore: 0.24,
    direction: "mixed",
    impactHorizon: "short_term",
  },
];
