export {
  NEWS_ENGINE_VERSION,
  NEWS_FEATURE_VERSION,
  NEWS_RELEVANCE_THRESHOLD,
  NEWS_SCORE_VERSION,
  buildCompanyNewsContext,
  extractNewsFeatures,
  generateNewsCandidates,
  recordNewsFeedback,
  scoreNewsFeatures,
  type ArticleInput,
  type CompanyInput,
  type CompanyNewsContext,
  type GeneratedNewsCandidate,
  type NewsFeedbackLabel,
  type NewsFeatureSet,
  type RelevanceScore,
} from "@/server/services/news-relevance-engine";
